name: Test All Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check accessibility of all files on GitHub Pages
        run: |
          BASE_URL="https://AwalidM.github.io/SPSSB"
          
          # Check accessibility for HTML files
          curl -s -o /dev/null -w "%{http_code}" $BASE_URL/index.html
          curl -s -o /dev/null -w "%{http_code}" $BASE_URL/home.html
          curl -s -o /dev/null -w "%{http_code}" $BASE_URL/login.html
          curl -s -o /dev/null -w "%{http_code}" $BASE_URL/signup.html
          curl -s -o /dev/null -w "%{http_code}" $BASE_URL/dashbord.html
          curl -s -o /dev/null -w "%{http_code}" $BASE_URL/slots.html
          
          # Check accessibility for JS files
          curl -s -o /dev/null -w "%{http_code}" $BASE_URL/auth.js
          curl -s -o /dev/null -w "%{http_code}" $BASE_URL/scripts.js
