name: Test HTML and JS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test if the HTML page loads (from GitHub Pages or direct URL)
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://<your-github-username>.github.io/<your-repository-name>/index.html
        continue-on-error: true
